### ISSUE TITLE
Executing getImage() on NULL value

### ISSUE THREAD

**Issue by bartoszherba** [mygento/coding-standard#1]
Sometimes in class 
**Rule/Design/RequestAwareBlockMethod**
occur exception because of line: 
**$name = mb_strtolower($node->getFirstChildOfType('Identifier')->getImage());**

It happen that **$node->getFirstChildOfType('Identifier')** is null which leads to:

`
PHP Fatal error:  Uncaught Error: Call to a member function getImage() on null in /var/www/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/RequestAwareBlockMethod.php:45
Stack trace:
#0 /var/www/vendor/phpmd/phpmd/src/main/php/PHPMD/RuleSet.php(284): Magento\CodeMessDetector\Rule\Design\RequestAwareBlockMethod->apply(Object(PHPMD\Node\MethodNode))
#1 /var/www/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(288): PHPMD\RuleSet->apply(Object(PHPMD\Node\MethodNode))
#2 /var/www/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(263): PHPMD\Parser->apply(Object(PHPMD\Node\MethodNode))
#3 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/ASTMethod.php(218): PHPMD\Parser->visitMethod(Object(PDepend\Source\AST\ASTMethod))
#4 /var/www/vendor/pdepend/pdepend/src/main/php/PDepend/Source/ASTVisitor/AbstractASTVisitor.php(110): PDepend\Source\AST\ASTMethod->accept(Object(PHPMD\Parser))
#5 /var/www/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(217): PDepend\Source\ASTVisitor\AbstractASTVisitor->visitClass(Ob in /var/www/dev/tests/static/framework/Magento/CodeMessDetector/Rule/Design/RequestAwareBlockMethod.php on line 45
`

**Comment by luckyraul** [comment]
resolved in a450527
